---
name: testing this file to call in another workflow

on:
  push: 
    branch: ["main"]
    
  pull-request:
    branch: ["main"]

  workflow_dispatch:
  
jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: to identify the file structure
        run: echo "Hurray"


