name: testing this file to call in another workflow

on:
  push: 
    branches: ["main"]
  pull_request:
    branches: ["main"]

#  workflow_dispatch:
  workflow_call:
  
jobs:
  test:
    runs-on: ubuntu-latest


    steps:
      - name: Test
        run: echo "Hurray"


